name: Koyeb Keep-Alive Cron

# Yeh script har 10 minute baad automatically chalegi
on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch: # Button se manual chalane ke liye

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Koyeb Backend
        run: |
          curl -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" \
          https://toxic-rhodie-bilalbasharat-ce9a70c1.koyeb.app/api/keep-alive
          